services:
    php:
        image: composer:2.8
        volumes:
            - .:/app
            - ${COMPOSER_HOME:-$HOME/.composer}:/composer
        networks:
            - app
        environment:
            - COMPOSER_ROOT_VERSION=dev-master
            - COMPOSER_HOME=/composer

networks:
    app:
        driver: bridge
